MODDICONV-234 Suppress MARC Authority Delete profiles from Data Import Settings UI
folio-org/data-import-raml-storage pull request #250
Opened 2022-02-21 13:59 UTC by ALiemeshka

## Purpose
Make MARC Authority Delete profiles hidden

## Approach
Extend job, match, action, mapping profiles schemas with new field:
  * name: hidden
  * type: boolean
  * default: false

## Learning
[https://issues.folio.org/browse/MODDICONV-234](MODDICONV-234)

2022-02-22 09:34 UTC, psmagin requested changes
You missed some points in approach:

- Update profiles that were created in [MODDICONV-228](https://issues.folio.org/browse/MODDICONV-228)

- Check if any migration scripts needed for other profiles

- Add new query parameter for endpoints:

query parameter requirements:
name: showHidden
type: boolean
required: false
default: false
endpoints to update:
GET /data-import-profiles/jobProfiles
GET /data-import-profiles/matchProfiles
GET /data-import-profiles/mappingProfiles
GET /data-import-profiles/actionProfiles

- Add tests to check this query parameter in updated endpoints

2022-02-22 09:34 UTC, psmagin commented on schemas/mod-data-import-converter-storage/actionProfile.json
> +      "description": "Flag indicates that the Action Profile will be visible on UI",
```suggestion
      "description": "Flag indicates that the Action Profile will be hidden on UI",
```

2022-02-22 10:57 UTC, ALiemeshka commented
> You missed some points in approach:
> 
>     * Update profiles that were created in [MODDICONV-228](https://issues.folio.org/browse/MODDICONV-228)
> 
>     * Check if any migration scripts needed for other profiles
> 
>     * Add new query parameter for endpoints:
> 
> 
> query parameter requirements: name: showHidden type: boolean required: false default: false endpoints to update: GET /data-import-profiles/jobProfiles GET /data-import-profiles/matchProfiles GET /data-import-profiles/mappingProfiles GET /data-import-profiles/actionProfiles
> 
>     * Add tests to check this query parameter in updated endpoints

It have implemented in another PR : https://github.com/folio-org/mod-data-import-converter-storage/pull/196

2022-03-02 10:09 UTC, viacheslavkol approved these changes

2022-03-08 19:08 UTC, psmagin approved these changes

2022-03-08 19:09 UTC, merged